config/routes.rb
CheckoutSystem::Application.routes.draw do

  match '/all', to: 'items#all'
  match '/return', to: 'items#return'
  resources :items

  root to: 'static_pages#home' 
  match '/show', to: 'items#show'
  match '/checkout', to: 'items#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :chemID, :name, :returned
  before_save { |item| item.chemID = chemID.downcase }
  validates :name, presence: true
  validates :chemID, presence: true
end
#http://limitless-harbor-5322.herokuapp.com/
##B70101

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #def show
  #	@item = Item.find(params[:id])
  #end

  def new
  	@item = Item.new()
  end

  def return
    item = Item.find(params[:format])
    if item.update_attributes(returned: true)
     flash[:error] = "Got it! Thanks for returning it!"
     redirect_to '/'
    else
      flash[:warning] = "Oops! Didn't save it"
      redirect_to '/'
    end
  end

  def show
  #	items = Item.all()
  end

  def create
  	@item = Item.new(params[:item])
  	if @item.save
#Need code Here
	# redirect_to @user
		flash[:error] = "Got it! Please bring it back soon!"
		redirect_to '/'
  	else
  		redirect_to 'checkout'
  	end
  end
  def destroy
    Item.find(params[:id]).destroy
    flash[:error] = "Item destroyed."
    redirect_to '/'
  end
#Don't know if I need new?
  #def new
  #end
end
#  background-image:url(assets/crissXcross.png); 
  #width:100%; 
  #height:auto;
#
#

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def checkout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "CHIMP"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/all.html.erb
<% provide(:title, 'All') %>
<h1>Reports</h1>

 <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th> Name </th>
      <th> ChemID </th>
      <th> Date Checked Out </th>
      <th> Date Returned </th>
    </tr>
  </thead>
  <tbody>
    <% Item.all.sort.reverse.each do |item| %>
     <tr>
       <td><%= item.name %></td>
       <td><%= item.chemID %></td>
       <td><%= item.created_at.to_s.split(' ').shift %></td>
       <% if(item.created_at==item.updated_at) %>
       <td> Not Returned </td>
       <% else %>
       <td><%= item.updated_at.to_s.split(' ').shift %></td>
       <% end %>
       <td><%= link_to "delete", item, method: :delete, data: { confirm: "You sure?" } %></td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<% provide(:title, 'Checkout') %>
<h1>Checkout</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@item) do |f| %>
      <% render 'shared/error_messages' %>

      <%= f.label :symbol, "Item Name" %>
      <%= f.text_field :name %>

      <%= f.label :symbol, "Chem ID" %>
      <%= f.text_field :chemID %>


      <%= f.submit "Checkout", class: "btn btn-large btn-danger" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, 'Return') %>
<h1>Items Out</h1>

 <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th> Name </th>
      <th> ChemID </th>
      <th> Date Checked Out </th>
      <th> Return </th>
    </tr>
  </thead>
  <tbody>
    <% Item.all.sort.reverse.each do |item| %>
    <% if(!item.returned) %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.chemID %></td>
      <td><%= item.created_at.to_s.split(' ').shift %></td>
      <td><%=link_to "Return", return_path(item)%></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by: Sean Slattery
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "C.H.I.M.P.", '/', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Checkout",    checkout_path %></li>
          <li><%= link_to "Return", show_path %></li>
          <li><%= link_to "Admin", all_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
   <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
	<h1>C.H.I.M.P.</h1>
	<h4>
  	Comp Help Inventory Management Program
	</h4>

	<%= link_to "Checkout", checkout_path, class: "btn btn-large btn-inverse"%>
	<%= link_to "Return", show_path, class: "btn btn-large btn-inverse"%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>